version: '3.8'

services:

  frontend:
    build: ./react-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./react-frontend:/app
      - /app/node_modules

  backend:
    build: ./flask-backend
    volumes:
      - ./flask-backend:/app
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
